MACOSX_SDK_VERSION:        # [osx]
  - '10.14'                # [osx and x86_64]
  - '13.0'                # [osx and arm64]
c_compiler_version:        # [osx]
  - 17                     # [osx]
cxx_compiler_version:      # [osx]
  - 17                     # [osx]
c_stdlib_version:          # [linux]
  - "2.17"                 # [linux]
channel_sources:
- freecad,conda-forge
channel_targets:
- freecad main